[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edsm"
version = "0.1.0"
description = "EDSM data ingestion utilities"
packages = ["functions", "scripts"]
include-package-data = true
